class QueryProvider:

    PRC_SELECT_EXC_R_FOR_WRITING = 'PKG_ERM_GENERATE_RATE.SELECT_EXC_R_FOR_WRITING'

    PRC_SELECT_REQUIRED_DATA_HDR = 'PKG_ERM_GENERATE_RATE.SELECT_REQUIRED_DATA_HDR'

    PRC_SELECT_REQUIRED_DATA_DTL = 'PKG_ERM_GENERATE_RATE.SELECT_REQUIRED_DATA_DTL'

    PRC_INSERT_GEN_RATE_FILE = 'PKG_ERM_GENERATE_RATE.INSERT_GEN_RATE_FILE'
