class QueryProvider:

	PRC_SELECT_REQUIRED_BANK = 'PKG_ERM_EXCHANGE_RATE.SELECT_REQUIRED_BANK'

	PRC_SELECT_ALL_SETTING_HDR = 'PKG_ERM_EXCHANGE_RATE.SELECT_ALL_SETTING_HDR'

	PRC_SELECT_SPECIFIC_SETTING_HDR = 'PKG_ERM_EXCHANGE_RATE.SELECT_SPECIFIC_SETTING_HDR'

	PRC_SELECT_REQUIRED_EXTRA = 'PKG_ERM_EXCHANGE_RATE.SELECT_REQUIRED_EXTRA'

	PRC_SELECT_REQUIRED_SETTING = 'PKG_ERM_EXCHANGE_RATE.SELECT_REQUIRED_SETTING'

	PRC_INSERT_EXCHANGE_RATE_HDR = 'PKG_ERM_EXCHANGE_RATE.INSERT_EXCHANGE_RATE_HDR'

	PRC_INSERT_EXCHANGE_RATE_DTL = 'PKG_ERM_EXCHANGE_RATE.INSERT_EXCHANGE_RATE_DTL'

	PRC_INSERT_EXCHANGE_RATE_BANK = 'PKG_ERM_EXCHANGE_RATE.INSERT_EXCHANGE_RATE_BANK'

	PRC_INSERT_ATTACH_FILE = 'PKG_ERM_EXCHANGE_RATE.INSERT_ERM_ATTACH_FILE'

	PRC_INSERT_HIST_LOG = 'PKG_ERM_EXCHANGE_RATE.INSERT_ERM_HIST_LOG'

	PRC_INSERT_AND_UPDATE_EXTRACT_REP = 'PKG_ERM_EXCHANGE_RATE.INS_N_UPD_ERM_EXTRACT_REP'

	PRC_DELTE_EXTRACT_REP = 'PKG_ERM_EXCHANGE_RATE.DELETE_ERM_EXTRACT_REP'

	PRC_SELECT_REF_EXCHANGE_RATE = 'PKG_ERM_EXCHANGE_RATE.SELECT_REF_EXCHANGE_RATE'