class QueryProvider:

    PRC_SELECT_REQUIRED_EXCHANGE_RATE_AUTO = 'PKG_ERM_EXCHANGE_RATE.SELECT_REQUIRED_EXC_RATE_AUTO'

    PRC_SELECT_REQUIRED_EXCHANGE_RATE_MANUAL = 'PKG_ERM_EXCHANGE_RATE.SELECT_REQUIRED_EXC_RATE_MAN'

    PRC_INSERT_EXCHANGE_RATE_HDR = 'PKG_ERM_EXCHANGE_RATE.INSERT_EXCHANGE_RATE_HDR'

    PRC_INSERT_EXCHANGE_RATE_DTL = 'PKG_ERM_EXCHANGE_RATE.INSERT_EXCHANGE_RATE_DTL'

    PRC_UPDATE_FK_RATE_DTL_AUTO = 'PKG_ERM_EXCHANGE_RATE.UPDATE_FK_RATE_DTL_AUTO'