class QueryProvider:

    QRY_SELECT_TOTAL_SCRAPING = 'SELECT COUNT(*) FROM ERM_SETTING_HDR WHERE RECORD_STATUS = \'A\' AND DELETE_FLAG = 0'

    PRC_SELECT_SCRAPING_FAIL_NIGHT = 'PKG_ERM_EMAIL.SELECT_SCRAPING_FAIL_NIGHT'

    PRC_SELECT_MANUAL_FAIL = 'PKG_ERM_EMAIL.SELECT_MANUAL_FAIL'

    PRC_SELECT_SCRAPING_FAIL_NOON = 'PKG_ERM_EMAIL.SELECT_SCRAPING_FAIL_NOON'

    PRC_SELECT_SCRAPING_REMAINING = 'PKG_ERM_EMAIL.SELECT_SCRAPING_REMAINING'

    PRC_SELECT_ALL_RECEIVERS = 'PKG_ERM_EMAIL.SELECT_ALL_RECEIVERS'